# Defaults (override from command line or mpconfigboard.mk)
BOARD_ENABLE_BMI08 ?= 1
BOARD_ENABLE_NRF24 ?= 1
BOARD_ENABLE_TRANSPORT_CORE ?= $(BOARD_ENABLE_NRF24)

ifeq ($(BOARD_ENABLE_BMI08),1)
BOSCH_DIR = $(USERMOD_DIR)/bosch/bmi08
SRC_USERMOD += $(USERMOD_DIR)/module_bmi08.c
SRC_USERMOD += $(BOSCH_DIR)/bmi08a.c
SRC_USERMOD += $(BOSCH_DIR)/bmi08g.c
SRC_USERMOD += $(BOSCH_DIR)/bmi08xa.c
CFLAGS_USERMOD += -I$(BOSCH_DIR) -DMODULE_BMI08_ENABLED=1
endif

ifeq ($(BOARD_ENABLE_NRF24),1)
SRC_USERMOD += $(USERMOD_DIR)/module_nrf24.c
SRC_USERMOD += $(USERMOD_DIR)/nrf24/nrf24.c
CFLAGS_USERMOD += -I$(USERMOD_DIR)/nrf24 -DMODULE_NRF24_ENABLED=1
endif

ifeq ($(BOARD_ENABLE_TRANSPORT_CORE),1)
ifneq ($(BOARD_ENABLE_NRF24),1)
$(error BOARD_ENABLE_TRANSPORT_CORE=1 requires BOARD_ENABLE_NRF24=1)
endif
SRC_USERMOD += $(USERMOD_DIR)/module_transport_core.c
SRC_USERMOD += $(USERMOD_DIR)/module_transport_event.c
SRC_USERMOD += $(USERMOD_DIR)/nrf24/transport_core.c
SRC_USERMOD += $(USERMOD_DIR)/nrf24/transport_event.c
SRC_USERMOD += $(USERMOD_DIR)/nrf24/transport_ring.c
SRC_USERMOD += $(USERMOD_DIR)/nrf24/transport_stm32.c
CFLAGS_USERMOD += -I$(USERMOD_DIR)/nrf24 -DMODULE_TRANSPORT_CORE_ENABLED=1
endif
